server:
  port: 8080
  servlet:
   context-path: /
   
spring:   
  datasource:
    url: jdbc:mysql://localhost:3306/pos?serverTimezone=Asia/Seoul
    username: pos
    password: cos1234
    driver-class-name: com.mysql.cj.jdbc.Driver
